config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :projects
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  namespace :admin do
    get :become
  end

  namespace :users_api, default: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          get :current
        end
      end

      resources :commits, only: [] do
        member do
          get :status
        end
      end
    end
  end

  namespace :api, default: { format: 'json' } do
    namespace :v1 do
      resources :projects, only: [] do
        collection do
          get :setup_data
          post :beacon
        end
      end
      resources :test_runs
      resources :test_jobs, only: [] do
        collection do
          patch :bind_next_batch
          patch :batch_update
        end
      end
    end
  end

  get 'oauth/github_callback' => 'oauth#github_callback', as: :github_callback
  get 'oauth/bitbucket_callback' => 'oauth#bitbucket_callback', as: :bitbucket_callback
  get 'oauth/authorize_bitbucket' => 'oauth#authorize_bitbucket', as: :authorize_bitbucket_access
  post 'webhooks/github' => 'webhooks#github', as: :github_webhook
  post 'webhooks/bitbucket' => 'webhooks#bitbucket', as: :bitbucket_webhook

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  get 'invitation/accept' => "user_invitations#accept", as: :accept_user_invitation
  # If you put this in the defaults(project: nil) block above it will erase
  # the "project" param from create action resulting in error.
  resources :projects, only: [:show, :update, :destroy] do
    resource :settings, only: [:show] do
      get :worker_setup
      get :notifications
    end

    resources :worker_groups, only: [:create, :update, :destroy] do
      member do
        post :reset_ssh_key
      end
    end

    member do
      get :instructions
      get :docker_compose
    end

    resources :test_runs, only: [:show, :update, :destroy] do
      member do
        post :retry
      end
    end

    resources :test_jobs, only: [] do
      put :retry
    end

    resources :tracked_branches, only: [:new, :create, :destroy],
      path: :branches, as: :branches do
        resources :test_runs, only: [:index, :create, :new]
    end

    resources :project_files, as: :files, path: :files, except: [:edit]
    resources :project_participations, as: :participations, path: :users
    resources :user_invitations, path: :invitations,
      except: [:index, :show, :update, :edit] do
      member do
        post :resend
      end
    end
  end

  resources :email_submissions, only: :create
  resources :feedback_submissions, only: :create
  resources :project_wizard, only: [:show, :update] do
    get :fetch_repos, on: :member
  end

  resource :dashboard, controller: :dashboard, only: [] do
    member do
      get :github_authorization_required
      get :bitbucket_authorization_required
    end
  end

  get 'pages/:id' => 'pages#show', as: :pages

  post 'live_updates/subscribe' => "live_updates#subscribe",
    as: :live_updates_subscribe

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard"
  before_filter :authenticate_user!
  # Skip setting the redirect_url in cookies in order to avoid redirecting the
  # user to this intermediate warning page, after returning from the provider's
  # authorization flow.
  skip_before_filter :set_redirect_url_in_cookie,
    only: [:github_authorization_required, :bitbucket_authorization_required]

  rescue_from Octokit::Unauthorized do |exception|
    if request.xhr?
      render json: { redirect_path: github_authorization_required_dashboard_path }
    else
      render action: :github_authorization_required
    end
  end

  rescue_from BitBucket::Error::Unauthorized do |exception|
    if request.xhr?
      render json: {redirect_path: bitbucket_authorization_required_dashboard_path }
    else
      render action: :bitbucket_authorization_required
    end
  end

  def index
    @projects = current_user.participating_projects.
      includes(tracked_branches: { test_runs: :test_jobs }).
      order(:repository_owner, :name)

    if @projects.empty?
      if current_user.can_create_new_project?
        redirect_to project_wizard_path(:select_repository)
      else
        email_link = view_context.mail_to("support@testributor.com", "Contact us")
        flash[:alert] =
          "You can't create any projects. #{email_link} if you think this is a mistake."
      end
    end
  end

  def current_ability
    @current_ability ||= Ability.new(current_user, current_project)
  end

  def github_authorization_required; end

  def bitbucket_authorization_required; end
end

app/views/dashboard/_no_branches.html.haml
%i
  No branches found for project #{project.owner_and_name}
  = link_to 'Add a branch',
    new_project_branch_path(project),
    class: 'btn btn-primary m-l-10'

app/views/dashboard/_test_run_actions.html.haml
= link_to retry_project_test_run_path(id: test_run.id,
  project_id: current_project),
  id: "test_run_retry_button",
  class: 'btn btn-primary btn-xs m-b-5 m-r-5',
  style: test_run.retry? ? '' : 'display: none',
  method: :post do

  %i.fa.fa-refresh
  %span Retry
- unless test_run.status.code.in? [TestStatus::CANCELLED, TestStatus::PASSED]
  = link_to project_test_run_path(current_project, test_run,
    status: TestStatus::CANCELLED), class: 'btn btn-xs btn-danger m-b-5', method: :put do
    .fa.fa-times
    %span Cancel

app/views/dashboard/bitbucket_authorization_required.html.haml
.panel.panel-color.panel-warning
  .panel-heading
    .panel-title
      Access to your BitBucket account was denied!
  .panel-body
    %h3
      It seems that you need to re-authorise Testributor to access your BitBucket
      account.
    %p
      There are two possible explanations for this:
    %p
      %ol
        %li
          You have manually revoked access to the Testributor OAuth application
          from your
          -# TODO We need to raise/rescue our own exception in order to pass
          -# additional information and correctly construct the following URL.
          #{link_to 'BitBucket Settings', 'https://bitbucket.org/account', target: '_blank'}.
        %li
          The action you just attempted requires you to approve additional
          BitBucket permissions for Testributor.
    %p
      = link_to "Authorize access", bitbucket_oauth_authorize_url, class: 'btn btn-primary'

app/views/dashboard/github_authorization_required.html.haml
.panel.panel-color.panel-warning
  .panel-heading
    .panel-title
      Access to your GitHub account was denied!
  .panel-body
    %h3
      It seems that you need to re-authorise Testributor to access your GitHub
      account.
    %p
      There are two possible explanations for this:
    %p
      %ol
        %li
          You have manually revoked access to the Testributor Authorized
          application from your
          #{link_to 'GitHub Settings', 'https://github.com/settings/applications', target: '_blank'}.
        %li
          The action you just attempted requires you to approve additional
          GitHub permissions for Testributor.
    %p
      = link_to "Authorize access", github_oauth_authorize_url, class: 'btn btn-primary'

app/views/dashboard/index.html.haml
= content_for :page_title do
  - if @projects.any?
    Your projects
  - else
    = "You haven't added any projects yet."
    = link_to "Add a project", project_wizard_path(:select_repository),
      class: 'btn btn-primary m-l-10'

- @projects.each do |project|
  .panel
    %h4= link_to project.owner_and_name, project_path(project)
    .panel-body
      .row
        .col-md-12
          - if project.tracked_branches.empty?
            = render partial: "no_branches",
              locals: { project: project}
          - else
            - project.tracked_branches.each do |branch|
              .col-md-12.branch
                .row
                  .col-sm-3.name
                    = link_to branch.branch_name,
                      project_branch_test_runs_path(branch.project, branch)
                  .col-sm-6
                    - if branch.last_run
                      = branch.last_run.decorate.commit_message
                      %br
                      %i= branch.last_run.decorate.commit_info
                  .col-sm-2
                    .status
                      %span{class: branch.status.try(:css_class)}
                        = branch.status.try(:text)
                  .col-md-1
                    .time
                      - if branch.last_run.try(:completed_at)
                        = time_ago_in_words(branch.last_run.completed_at)