config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :projects
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  namespace :admin do
    get :become
  end

  namespace :users_api, default: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          get :current
        end
      end

      resources :commits, only: [] do
        member do
          get :status
        end
      end
    end
  end

  namespace :api, default: { format: 'json' } do
    namespace :v1 do
      resources :projects, only: [] do
        collection do
          get :setup_data
          post :beacon
        end
      end
      resources :test_runs
      resources :test_jobs, only: [] do
        collection do
          patch :bind_next_batch
          patch :batch_update
        end
      end
    end
  end

  get 'oauth/github_callback' => 'oauth#github_callback', as: :github_callback
  get 'oauth/bitbucket_callback' => 'oauth#bitbucket_callback', as: :bitbucket_callback
  get 'oauth/authorize_bitbucket' => 'oauth#authorize_bitbucket', as: :authorize_bitbucket_access
  post 'webhooks/github' => 'webhooks#github', as: :github_webhook
  post 'webhooks/bitbucket' => 'webhooks#bitbucket', as: :bitbucket_webhook

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  get 'invitation/accept' => "user_invitations#accept", as: :accept_user_invitation
  # If you put this in the defaults(project: nil) block above it will erase
  # the "project" param from create action resulting in error.
  resources :projects, only: [:show, :update, :destroy] do
    resource :settings, only: [:show] do
      get :worker_setup
      get :notifications
    end

    resources :worker_groups, only: [:create, :update, :destroy] do
      member do
        post :reset_ssh_key
      end
    end

    member do
      get :instructions
      get :docker_compose
    end

    resources :test_runs, only: [:show, :update, :destroy] do
      member do
        post :retry
      end
    end

    resources :test_jobs, only: [] do
      put :retry
    end

    resources :tracked_branches, only: [:new, :create, :destroy],
      path: :branches, as: :branches do
        resources :test_runs, only: [:index, :create, :new]
    end

    resources :project_files, as: :files, path: :files, except: [:edit]
    resources :project_participations, as: :participations, path: :users
    resources :user_invitations, path: :invitations,
      except: [:index, :show, :update, :edit] do
      member do
        post :resend
      end
    end
  end

  resources :email_submissions, only: :create
  resources :feedback_submissions, only: :create
  resources :project_wizard, only: [:show, :update] do
    get :fetch_repos, on: :member
  end

  resource :dashboard, controller: :dashboard, only: [] do
    member do
      get :github_authorization_required
      get :bitbucket_authorization_required
    end
  end

  get 'pages/:id' => 'pages#show', as: :pages

  post 'live_updates/subscribe' => "live_updates#subscribe",
    as: :live_updates_subscribe

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
end

app/models/project_participation.rb
class ProjectParticipation < ActiveRecord::Base
  self.table_name = :projects_users

  belongs_to :project
  belongs_to :user
  has_many :branch_notification_settings, dependent: :destroy

  after_create :create_branch_notification_settings
  after_destroy :remove_invitation_if_any

  accepts_nested_attributes_for :branch_notification_settings

  private

  def remove_invitation_if_any
    project.user_invitations.where(user: user).each(&:destroy)
  end

  def create_branch_notification_settings
    project.tracked_branches.each do |branch|
      self.branch_notification_settings.create!(
        tracked_branch: branch,
        notify_on: self.new_branch_notify_on)
    end
  end
end

app/controllers/project_participations_controller.rb
class ProjectParticipationsController < DashboardController
  include Controllers::EnsureProject

  before_action :set_participation, only: [:update, :destroy]

  def index
    @participations = current_project.project_participations.includes(:user)
    @invitations = current_project.user_invitations.pending.includes(:user)
  end

  def destroy
    authorize! :destroy, @participation

    if @participation.destroy
      if @participation.user == current_user
        flash[:notice] =
          "You are no longer a member of #{@participation.project.name} project"
        redirect_to authenticated_root_path
      else
        flash[:notice] = "User is no longer a member of this project"
        redirect_to :back
      end
    else
      flash[:alert] = @participation.errors.full_messages.to_sentence
      redirect_to :back
    end
  end

  def update
    authorize! :update, @participation

    if @participation.update(participation_params)
      flash[:notice] = "Your options were saved"
    else
      flash[:alert] = @participation.errors.full_messages.to_sentence
    end

    redirect_to :back
  end

  private

  def set_participation
    @participation = current_project.project_participations.find(params[:id])
  end

  def participation_params
    params.require(:project_participation).
      permit(:new_branch_notify_on,
             branch_notification_settings_attributes: [:notify_on, :tracked_branch_id, :id])
  end
end

app/views/project_participations/index.html.haml
- breadcrumb :project_participations, current_project

- content_for :page_title do
  Users

.panel.panel-default
  .panel-body
    .row
      .col-md-12.col-sm-12.col-xs-12
        - if can? :manage, current_project
          = link_to new_project_user_invitation_path(current_project), class: 'btn btn-default' do
            %i.fa.fa-users
            %span.nav-label= t('invite_users')
        - if @participations.any?
          %h3 Users
          %table.table
            %thead
              %tr
                %th= "Email"
                %th= "Participated at"
                %th= "Actions"
            %tbody
              - @participations.each do |participation|
                %tr
                  %td= participation.user.email
                  %td= l(participation.created_at.to_date, format: :default)
                  %td
                    - if can? :destroy, participation
                      :ruby
                        message = if participation.user == current_user
                          "You are leaving this project. Are you sure?"
                        else
                          "The user will not be able to use this project, are you sure?"
                        end

                      = link_to(project_participation_path(current_project, participation),
                        method: :delete, class: 'btn btn-danger',
                        data: { confirm: message }) do
                        %i.fa.fa-remove
                        Revoke access
        - else
          %br
          %h3
            No other users participating in this project

        - if can?(:manage, current_project) && @invitations.any?
          %h3 Invitations
          %table.table
            %thead
              %tr
                %th= "Email"
                %th= "Invited at"
                %th= "Actions"
            %tbody
              - @invitations.each do |invitation|
                %tr
                  %td= invitation.email
                  %td= l(invitation.created_at.to_date, format: :default)
                  %td
                    = link_to(resend_project_user_invitation_path(current_project, invitation),
                      method: :post, class: 'btn btn-default') do
                      %i.fa.fa-envelope-o
                      Resend invitation
                    = link_to(project_user_invitation_path(current_project, invitation),
                      method: :delete, class: 'btn btn-danger',
                      data: { confirm: "Are you sure?" }) do
                      %i.fa.fa-remove
                      Cancel invitation