config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :projects
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  namespace :admin do
    get :become
  end

  namespace :users_api, default: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          get :current
        end
      end

      resources :commits, only: [] do
        member do
          get :status
        end
      end
    end
  end

  namespace :api, default: { format: 'json' } do
    namespace :v1 do
      resources :projects, only: [] do
        collection do
          get :setup_data
          post :beacon
        end
      end
      resources :test_runs
      resources :test_jobs, only: [] do
        collection do
          patch :bind_next_batch
          patch :batch_update
        end
      end
    end
  end

  get 'oauth/github_callback' => 'oauth#github_callback', as: :github_callback
  get 'oauth/bitbucket_callback' => 'oauth#bitbucket_callback', as: :bitbucket_callback
  get 'oauth/authorize_bitbucket' => 'oauth#authorize_bitbucket', as: :authorize_bitbucket_access
  post 'webhooks/github' => 'webhooks#github', as: :github_webhook
  post 'webhooks/bitbucket' => 'webhooks#bitbucket', as: :bitbucket_webhook

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  get 'invitation/accept' => "user_invitations#accept", as: :accept_user_invitation
  # If you put this in the defaults(project: nil) block above it will erase
  # the "project" param from create action resulting in error.
  resources :projects, only: [:show, :update, :destroy] do
    resource :settings, only: [:show] do
      get :worker_setup
      get :notifications
    end

    resources :worker_groups, only: [:create, :update, :destroy] do
      member do
        post :reset_ssh_key
      end
    end

    member do
      get :instructions
      get :docker_compose
    end

    resources :test_runs, only: [:show, :update, :destroy] do
      member do
        post :retry
      end
    end

    resources :test_jobs, only: [] do
      put :retry
    end

    resources :tracked_branches, only: [:new, :create, :destroy],
      path: :branches, as: :branches do
        resources :test_runs, only: [:index, :create, :new]
    end

    resources :project_files, as: :files, path: :files, except: [:edit]
    resources :project_participations, as: :participations, path: :users
    resources :user_invitations, path: :invitations,
      except: [:index, :show, :update, :edit] do
      member do
        post :resend
      end
    end
  end

  resources :email_submissions, only: :create
  resources :feedback_submissions, only: :create
  resources :project_wizard, only: [:show, :update] do
    get :fetch_repos, on: :member
  end

  resource :dashboard, controller: :dashboard, only: [] do
    member do
      get :github_authorization_required
      get :bitbucket_authorization_required
    end
  end

  get 'pages/:id' => 'pages#show', as: :pages

  post 'live_updates/subscribe' => "live_updates#subscribe",
    as: :live_updates_subscribe

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :about_to_be_destroyed

  include Models::RedisLiveUpdates

  ACTIVE_WORKER_THRESHOLD_SECONDS = 20

  devise :database_authenticatable

  belongs_to :user # this is the owner of the project
  belongs_to :docker_image # This is the base image

  has_one :docker_image_selection

  has_many :tracked_branches, dependent: :destroy, inverse_of: :project
  has_many :test_runs
  has_many :test_jobs, through: :test_runs
  has_many :project_participations, dependent: :destroy
  has_many :members, through: :project_participations, class_name: "User",
    source: :user
  has_many :user_invitations, dependent: :destroy
  has_many :invited_users, through: :user_invitations, class_name: 'User',
    source: :user
  has_many :project_files, dependent: :destroy
  has_many :oauth_applications, class_name: 'Doorkeeper::Application',
    as: :owner, dependent: :destroy
  has_many :worker_groups, dependent: :destroy
  has_many :technology_selections, dependent: :destroy
  has_many :technologies, through: :technology_selections

  validates :name, :user, presence: true
  validates :name, uniqueness: { scope: :user }
  validate :check_user_limit, if: :user_id_changed?

  before_create :set_secure_random
  # Set this flag to true in order to destroy testributor.yml and
  # build_commands.sh which can't be deleted otherwise.
  # Use prepend: true to guarantee that it is called before childrens'
  # destroy methods.
  before_destroy :set_about_to_be_destroyed, prepend: true
  # TODO: Run cron job to ensure all owners are also participants
  after_create :add_owner_to_participants
  after_create :create_build_commands_file

  attr_accessor :fork

  scope :bitbucket, ->{ where(repository_provider: 'bitbucket') }
  scope :github, ->{ where(repository_provider: 'github') }

  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-').downcase}"
  end

  def workers_redis_key
    "project_#{id}_workers"
  end

  # Updates the project's set of workers with only the active
  # and returns the list of active worker uuids
  # Only this method should be called to find the active workers since directly
  # quering for the key in Redis will not clean up the list
  # http://stackoverflow.com/a/8833058
  def update_active_workers
    redis = Katana::Application.redis
    key = workers_redis_key
    active = redis.sort(key, by: 'nosort', get: '*').compact
    redis.multi do
      redis.del(key)
      redis.sadd(key, active) if active.any?
    end

    active
  end
  alias :active_workers :update_active_workers

  def owner_and_name
    "#{repository_owner}/#{repository_name}"
  end

  def create_oauth_application!
    WorkerGroup.transaction do
      oauth_application = oauth_applications.create!(
        name: repository_id || repository_slug,
        redirect_uri: Katana::Application::HEROKU_URL
      )
      worker_groups.create!(oauth_application: oauth_application,
        friendly_name: "#{name} Worker Group #{oauth_applications.count}")
    end
  end

  def destroy_oauth_application!(oauth_application_id)
    oauth_application = oauth_applications.find(oauth_application_id)
    WorkerGroup.transaction do
      worker_groups.where(oauth_application_id: oauth_application_id).
        each(&:destroy!)
      oauth_application.destroy!
    end
  end

  def generate_docker_compose_yaml(oauth_app_id)
    return false if docker_image.blank?

    oauth_application = oauth_applications.find(oauth_app_id)
    attributes_hash = {}

    # Add linked images
    technologies.each do |technology|
      data = technology.docker_compose_data
      image_attributes = {}
      image_attributes["image"] = technology.hub_image
      if data["environment"].present?
        image_attributes["environment"] = data["environment"]
      end
      attributes_hash[technology.standardized_name] = image_attributes
    end

    # Now add the base image
    base_image_attributes = {}
    base_image_attributes["image"] = docker_image.hub_image
    base_image_attributes["command"] = "/bin/bash -l get_and_run_testributor.sh"
    if technologies.any?
      base_image_attributes["links"] = technologies.map do |tech|
        link = tech.standardized_name
        if tech.docker_compose_data["alias"]
          link += ":#{tech.docker_compose_data["alias"]}"
        end

        link
      end
    end
    base_image_attributes["environment"] = {
      'APP_ID' => oauth_application.uid,
      'APP_SECRET' => oauth_application.secret,
      'API_URL' => "http://www.testributor.com/api/v1/"
    }

    # Merge any additional base image variables
    if docker_image.docker_compose_data["environment"]
      base_image_attributes["environment"].merge!(
        docker_image.docker_compose_data["environment"])
    end
    attributes_hash[docker_image.standardized_name] = base_image_attributes

    attributes_hash.to_yaml
  end

  # For now we simply create the file based on a template. In the future
  # we might want to "look" at the code to decide about the code, testing
  # framework etc to be able to build a more sophisticated yml file.
  def create_testributor_yml_file!
    testributor_yml_file =
      project_files.find_or_initialize_by(path: ProjectFile::JOBS_YML_PATH)
    testributor_yml_file.contents = File.read(
      File.join(Rails.root, 'app', 'file_templates', ProjectFile::JOBS_YML_PATH))

    testributor_yml_file.save!
  end

  private

  def set_about_to_be_destroyed
    self.about_to_be_destroyed = true
  end

  # Don't let a project be assigned to a user if projects limit
  # has been reached
  def check_user_limit
    if user && !user.can_create_new_project?
      errors.add(:base, :project_limit_reached)
    end
  end

  # TODO: Add tests for this
  def add_owner_to_participants
    self.members << self.user
  end

  def create_build_commands_file
    self.project_files.create!(path: ProjectFile::BUILD_COMMANDS_PATH)
  end

  def set_secure_random
    self.secure_random = SecureRandom.hex

    #in case a secure random exists
    while Project.find_by_secure_random(self.secure_random)
      self.secure_random = SecureRandom.hex
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < DashboardController
  include Controllers::EnsureProject

  def show
  end

  def worker_setup
  end

  def notifications
  end
end

app/views/settings/_settings_common_header.html.haml
- content_for :page_title do
  Project settings

%ul.nav.nav-tabs
  - link = project_settings_path(current_project)
  %li{ class: current_page?(link) ? 'active' : nil }
    = link_to "General", link
  - link = worker_setup_project_settings_path(current_project)
  %li{ class: current_page?(link) ? 'active' : nil }
    = link_to "Worker setup", link
  - link = notifications_project_settings_path(current_project)
  %li{ class: current_page?(link) ? 'active' : nil }
    = link_to "Notifications", link

app/views/settings/notifications.html.haml
- breadcrumb :settings, current_project

= render 'settings_common_header'

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Email notifications
  .panel-body
    .row
      .col-xs-12
        These are settings only for you. Other users participating in this project
        might have different notification settings.
      .col-md-6
        %br
        %strong When do you want to receive email notifications?
        = simple_form_for current_user.participation_for_project(current_project),
          url: project_participation_path(current_project, current_user.participation_for_project(current_project)),
          wrapper: "horizontal_form" do |f|

          .col-xs-12
            %h4 New branches
            .col-xs-12.form-row
              = f.input :new_branch_notify_on, as: :select,
                collection: BranchNotificationSetting::NOTIFY_ON_MAP_HUMAN.invert,
                include_blank: false, label: "Default setting"

          .col-xs-12
            %h4 Existing branches

            = f.simple_fields_for :branch_notification_settings do |ff|
              .col-xs-12.form-row
                = ff.input :notify_on, as: :select,
                  collection: BranchNotificationSetting::NOTIFY_ON_MAP_HUMAN.invert,
                  include_blank: false, label: ff.object.tracked_branch.branch_name
                = ff.input :tracked_branch_id, as: :hidden
                = ff.input :id, as: :hidden

          .col-xs-12
            = f.submit "Save", class: 'btn btn-primary'

app/views/settings/show.html.haml
- breadcrumb :settings, current_project

= render 'settings_common_header'

.tab-content
  - if can? :manage, current_project
    .well
      %strong Delete project from Testributor (cannot be reverted): 
      = link_to "Delete", project_path(current_project), method: :delete,
        data: { confirm: "'#{current_project.name}' project will be deleted. Are you sure?" },
        class: 'btn btn-danger'
  - else
    - # Remove this when we add general settings which the non-owner users can change
    .alert.alert-danger Only the owner of this project can edit these settings

app/views/settings/worker_setup.html.haml
- breadcrumb :settings, current_project

= render 'settings_common_header'

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Worker Groups
      .worker-groups-actions
        = link_to project_worker_groups_path(current_project), method: :post,
        class: 'btn btn-success btn-xs',
        title: 'Create a new group of workers.' do
          %i.fa.fa-plus-square
          Add a new group
  .panel-body
    %table.table
      %thead
        %tr
          %th
            Friendly name
          %th
      %tbody
        - current_project.worker_groups.each do |worker_group|
          %tr
            %td.worker-group
              = render worker_group
            %td
              .worker-group-actions
                = link_to docker_compose_project_path(current_project, client_id: worker_group.oauth_application_id),
                class: 'btn btn-info btn-xs',
                title: 'Download the docker-compose.yml file that is needed for creating a worker.' do
                  %i.fa.fa-download
                  docker-compose.yml
                = link_to reset_ssh_key_project_worker_group_path(current_project, worker_group),
                method: :post, class: 'btn btn-danger btn-xs',
                data: { confirm: 'Workers of this group will need to be restarted after resetting the key. Reset?' },
                title: 'Reset the SSH key that the workers of this group use in order to access the repository linked with this project.' do
                  %i.fa.fa-refresh
                  Reset SSH key
                = link_to project_worker_group_path(current_project, worker_group),
                method: :delete, class: 'btn btn-danger btn-xs',
                data: { confirm: "Workers of this group will not be able to access project '#{current_project.name}' anymore. Delete?" },
                title: 'Delete the group and disable its workers from accessing this project.' do
                  %i.fa.fa-trash
                  Delete group

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Language and technologies
  .panel-body
    = form_for current_project do |f|
      .col-xs-6
        %h3 Language
        = f.select :docker_image_id,
          grouped_options_for_select(grouped_languages_options,
          f.object.docker_image_id)
      .col-xs-6
        %h3 Technologies
        = f.select :technology_ids,
          options_for_select(technologies_options, f.object.technology_ids),
          {}, multiple: true, class: 'multi-select'
      .col-xs-12
        .pull-right.m-t-15
          = f.submit "Save", class: 'btn btn-primary w-lg btn-lg'