config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper

  authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :projects
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  namespace :admin do
    get :become
  end

  namespace :users_api, default: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          get :current
        end
      end

      resources :commits, only: [] do
        member do
          get :status
        end
      end
    end
  end

  namespace :api, default: { format: 'json' } do
    namespace :v1 do
      resources :projects, only: [] do
        collection do
          get :setup_data
          post :beacon
        end
      end
      resources :test_runs
      resources :test_jobs, only: [] do
        collection do
          patch :bind_next_batch
          patch :batch_update
        end
      end
    end
  end

  get 'oauth/github_callback' => 'oauth#github_callback', as: :github_callback
  get 'oauth/bitbucket_callback' => 'oauth#bitbucket_callback', as: :bitbucket_callback
  get 'oauth/authorize_bitbucket' => 'oauth#authorize_bitbucket', as: :authorize_bitbucket_access
  post 'webhooks/github' => 'webhooks#github', as: :github_webhook
  post 'webhooks/bitbucket' => 'webhooks#bitbucket', as: :bitbucket_webhook

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  get 'invitation/accept' => "user_invitations#accept", as: :accept_user_invitation
  # If you put this in the defaults(project: nil) block above it will erase
  # the "project" param from create action resulting in error.
  resources :projects, only: [:show, :update, :destroy] do
    resource :settings, only: [:show] do
      get :worker_setup
      get :notifications
    end

    resources :worker_groups, only: [:create, :update, :destroy] do
      member do
        post :reset_ssh_key
      end
    end

    member do
      get :instructions
      get :docker_compose
    end

    resources :test_runs, only: [:show, :update, :destroy] do
      member do
        post :retry
      end
    end

    resources :test_jobs, only: [] do
      put :retry
    end

    resources :tracked_branches, only: [:new, :create, :destroy],
      path: :branches, as: :branches do
        resources :test_runs, only: [:index, :create, :new]
    end

    resources :project_files, as: :files, path: :files, except: [:edit]
    resources :project_participations, as: :participations, path: :users
    resources :user_invitations, path: :invitations,
      except: [:index, :show, :update, :edit] do
      member do
        post :resend
      end
    end
  end

  resources :email_submissions, only: :create
  resources :feedback_submissions, only: :create
  resources :project_wizard, only: [:show, :update] do
    get :fetch_repos, on: :member
  end

  resource :dashboard, controller: :dashboard, only: [] do
    member do
      get :github_authorization_required
      get :bitbucket_authorization_required
    end
  end

  get 'pages/:id' => 'pages#show', as: :pages

  post 'live_updates/subscribe' => "live_updates#subscribe",
    as: :live_updates_subscribe

  get '/sitemap.xml.gz', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3.amazonaws.com/sitemaps/sitemap.xml.gz"), as: :sitemap
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessor :about_to_be_destroyed

  include Models::RedisLiveUpdates

  ACTIVE_WORKER_THRESHOLD_SECONDS = 20

  devise :database_authenticatable

  belongs_to :user # this is the owner of the project
  belongs_to :docker_image # This is the base image

  has_one :docker_image_selection

  has_many :tracked_branches, dependent: :destroy, inverse_of: :project
  has_many :test_runs
  has_many :test_jobs, through: :test_runs
  has_many :project_participations, dependent: :destroy
  has_many :members, through: :project_participations, class_name: "User",
    source: :user
  has_many :user_invitations, dependent: :destroy
  has_many :invited_users, through: :user_invitations, class_name: 'User',
    source: :user
  has_many :project_files, dependent: :destroy
  has_many :oauth_applications, class_name: 'Doorkeeper::Application',
    as: :owner, dependent: :destroy
  has_many :worker_groups, dependent: :destroy
  has_many :technology_selections, dependent: :destroy
  has_many :technologies, through: :technology_selections

  validates :name, :user, presence: true
  validates :name, uniqueness: { scope: :user }
  validate :check_user_limit, if: :user_id_changed?

  before_create :set_secure_random
  # Set this flag to true in order to destroy testributor.yml and
  # build_commands.sh which can't be deleted otherwise.
  # Use prepend: true to guarantee that it is called before childrens'
  # destroy methods.
  before_destroy :set_about_to_be_destroyed, prepend: true
  # TODO: Run cron job to ensure all owners are also participants
  after_create :add_owner_to_participants
  after_create :create_build_commands_file

  attr_accessor :fork

  scope :bitbucket, ->{ where(repository_provider: 'bitbucket') }
  scope :github, ->{ where(repository_provider: 'github') }

  def to_param
    "#{id}-#{name.gsub(/[^a-z0-9]+/i, '-').downcase}"
  end

  def workers_redis_key
    "project_#{id}_workers"
  end

  # Updates the project's set of workers with only the active
  # and returns the list of active worker uuids
  # Only this method should be called to find the active workers since directly
  # quering for the key in Redis will not clean up the list
  # http://stackoverflow.com/a/8833058
  def update_active_workers
    redis = Katana::Application.redis
    key = workers_redis_key
    active = redis.sort(key, by: 'nosort', get: '*').compact
    redis.multi do
      redis.del(key)
      redis.sadd(key, active) if active.any?
    end

    active
  end
  alias :active_workers :update_active_workers

  def owner_and_name
    "#{repository_owner}/#{repository_name}"
  end

  def create_oauth_application!
    WorkerGroup.transaction do
      oauth_application = oauth_applications.create!(
        name: repository_id || repository_slug,
        redirect_uri: Katana::Application::HEROKU_URL
      )
      worker_groups.create!(oauth_application: oauth_application,
        friendly_name: "#{name} Worker Group #{oauth_applications.count}")
    end
  end

  def destroy_oauth_application!(oauth_application_id)
    oauth_application = oauth_applications.find(oauth_application_id)
    WorkerGroup.transaction do
      worker_groups.where(oauth_application_id: oauth_application_id).
        each(&:destroy!)
      oauth_application.destroy!
    end
  end

  def generate_docker_compose_yaml(oauth_app_id)
    return false if docker_image.blank?

    oauth_application = oauth_applications.find(oauth_app_id)
    attributes_hash = {}

    # Add linked images
    technologies.each do |technology|
      data = technology.docker_compose_data
      image_attributes = {}
      image_attributes["image"] = technology.hub_image
      if data["environment"].present?
        image_attributes["environment"] = data["environment"]
      end
      attributes_hash[technology.standardized_name] = image_attributes
    end

    # Now add the base image
    base_image_attributes = {}
    base_image_attributes["image"] = docker_image.hub_image
    base_image_attributes["command"] = "/bin/bash -l get_and_run_testributor.sh"
    if technologies.any?
      base_image_attributes["links"] = technologies.map do |tech|
        link = tech.standardized_name
        if tech.docker_compose_data["alias"]
          link += ":#{tech.docker_compose_data["alias"]}"
        end

        link
      end
    end
    base_image_attributes["environment"] = {
      'APP_ID' => oauth_application.uid,
      'APP_SECRET' => oauth_application.secret,
      'API_URL' => "http://www.testributor.com/api/v1/"
    }

    # Merge any additional base image variables
    if docker_image.docker_compose_data["environment"]
      base_image_attributes["environment"].merge!(
        docker_image.docker_compose_data["environment"])
    end
    attributes_hash[docker_image.standardized_name] = base_image_attributes

    attributes_hash.to_yaml
  end

  # For now we simply create the file based on a template. In the future
  # we might want to "look" at the code to decide about the code, testing
  # framework etc to be able to build a more sophisticated yml file.
  def create_testributor_yml_file!
    testributor_yml_file =
      project_files.find_or_initialize_by(path: ProjectFile::JOBS_YML_PATH)
    testributor_yml_file.contents = File.read(
      File.join(Rails.root, 'app', 'file_templates', ProjectFile::JOBS_YML_PATH))

    testributor_yml_file.save!
  end

  private

  def set_about_to_be_destroyed
    self.about_to_be_destroyed = true
  end

  # Don't let a project be assigned to a user if projects limit
  # has been reached
  def check_user_limit
    if user && !user.can_create_new_project?
      errors.add(:base, :project_limit_reached)
    end
  end

  # TODO: Add tests for this
  def add_owner_to_participants
    self.members << self.user
  end

  def create_build_commands_file
    self.project_files.create!(path: ProjectFile::BUILD_COMMANDS_PATH)
  end

  def set_secure_random
    self.secure_random = SecureRandom.hex

    #in case a secure random exists
    while Project.find_by_secure_random(self.secure_random)
      self.secure_random = SecureRandom.hex
    end
  end
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApiController
      # We ignore counting active workers for "current" action to avoid showing
      # the workers active during initialization. Initialization
      # take some time to complete and workers will appear as inactive
      # for some seconds.

      skip_before_action :worker_report, only: :setup_data

      def setup_data
        render json: {
          current_project:
            ActiveModel::SerializableResource.new(current_project),
          current_worker_group:
            ActiveModel::SerializableResource.new(current_worker_group)
        }
      end

      def beacon
        head :ok
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < DashboardController
  include ApplicationHelper
  include Controllers::EnsureProject

  skip_before_action :ensure_project_exists!, only: [:destroy]

  def show
    @branches = current_project.tracked_branches.
      includes(test_runs: :test_jobs)
  end

  def instructions
  end

  def update
    notice = nil
    alert = nil
    begin
      current_project.assign_attributes(project_params)
      current_project.technologies = DockerImage.technologies.
        where(id: project_params[:technology_ids])
      current_project.save
      notice = "Project successfully updated"
    rescue ActiveRecord::RecordInvalid => invalid
      alert = invalid.record.errors.messages.values.join(', ')
    end

    respond_to do |fmt|
      fmt.json do
        yml_contents = current_project.generate_docker_compose_yaml(
          current_project.worker_groups.first.oauth_application_id)

        render json: { notice: notice, alert: alert,
                       docker_compose_yml_contents: yml_contents }
      end

      fmt.html do
        flash[:notice] = notice
        flash[:alert] = alert
        redirect_to :back
      end
    end
  end

  def destroy
    project = current_user.projects.find(params[:id])

    if project.destroy
      manager = RepositoryManager.new(project)
      manager.cleanup_for_removal

      flash[:notice] =
        "Successfully destroyed '#{project.name}' project."
    else
      flash[:alert] =
        "Could not destroy '#{project.name}' project."
    end

    redirect_to root_path
  end

  def docker_compose
    send_data current_project.generate_docker_compose_yaml(params[:client_id]),
      type: 'text/yml; charset=UTF-8;',
      disposition: 'attachment; filename=docker-compose.yml'
  end

  private

  def current_project
    super(:id)
  end

  def project_params
    params.require(:project).permit(:docker_image_id, technology_ids: [])
  end

  def api_client_params
    params.require(:api_client).permit(:oauth_application_id, :ssh_key_private,
      :ssh_key_provider_friendly_name)
  end
end

app/views/projects/instructions.html.haml
- breadcrumb :project_instructions, current_project

- content_for :page_title do
  Instructions

.panel.panel-default
  .panel-heading
    %h3 Create any needed non tracked files
  .panel-body
    %p
      In many projects there are files which are not tracked by the version control
      system to let developers use different versions in their machines.
      %br
      Still some of them are needed for a successfull test suite run.
    %p
      An example is the
      %strong "config/database.yml"
      file in a Rails application which holds the information
      on how to connect to the database.
      %br
        = "You can create or override any project files #{link_to "here", project_files_path(current_project)}.".html_safe

      %br
      %strong= ProjectFile::JOBS_YML_PATH
      file is the one that describes the jobs that constitute
      each test run and for this reason it cannot be deleted.

.panel.panel-default
  .panel-heading
    %h3 Create a worker on your machine

  .panel-body
    %ol
      %li
        Install docker and docker-compose.
        You can find instructions on how to do that on the
        #{link_to ' official Docker site', 'https://docs.docker.com/'}.

      %li
        Download a docker-compose.yml file for this project.
        %br
        You can create groups of workers in the relevant
        = link_to "Settings", worker_setup_project_settings_path(current_project)
        page.
        Each group will have its own docker-compose.yml file with different
        set of credentials on Testributor and different ssh key to access the
        code.
        This way, if you want to revoke access to some
        workers, you don't have to setup the rest of the workers too.

        - if worker_group = current_project.worker_groups.first
          %br
          This is the docker-compose.yml file for your first worker group:
          %p
            = link_to docker_compose_project_path(current_project, client_id: worker_group.oauth_application_id),
              class: "btn btn-default" do
              Download
              %i.fa.fa-download

      %li
        Create a worker by running the following command in the same directory where
        you saved the docker-compose.yml file:
        %p
          %code docker-compose up
        For more options and documentation on docker-compose visit the
        #{link_to 'official Docker site', 'https://docs.docker.com/compose/'}.

app/views/projects/settings.html.haml
- breadcrumb :settings, current_project

- content_for :page_title do
  Settings

.panel-body
  .panel.panel-default
    .panel-heading
      %h3.panel-title Instructions
    .panel-body
      Read the instructions on how to setup your project
      = link_to("here", instructions_project_path(current_project))

  .panel.panel-default
    .panel-heading
      %h3.panel-title
        Worker Groups
        (#{link_to 'add another', create_worker_group_project_path(current_project), method: :post})
    .panel-body
      - current_project.oauth_applications.each do |app|
        .well
          %p
            %strong
              Configuration file:
            %code
              docker-compose.yml
            = link_to docker_compose_project_path(current_project, client_id: app.id),
            class: 'btn btn-primary btn-xs' do
              %i.fa.fa-download
              Download
          %p
            :ruby
              api_client = current_project.
                find_or_initialize_api_client_by_oauth_application_id(app.id)
            = render partial: api_client.ssh_key_private.blank? ? 'ssh_key_form' : 'ssh_key_delete',
            locals: {api_client: api_client, repository_provider: current_project.repository_provider}
          %p
            = link_to delete_worker_group_project_path(client_id: app.id),
            method: :delete, class: 'btn btn-danger btn-lg' do
              %i.fa.fa-trash
              Delete Group

  .panel.panel-default
    .panel-heading
      %h3.panel-title
        Language and technologies
    .panel-body
      = form_for current_project, url: project_path do |f|
        .col-xs-6
          %h3 Language
          = f.select :docker_image_id,
            grouped_options_for_select(grouped_languages_options,
            f.object.docker_image_id)
        .col-xs-6
          %h3 Technologies
          = f.select :technology_ids,
            options_for_select(technologies_options, f.object.technology_ids),
            {}, multiple: true, class: 'multi-select'
        .col-xs-12
          .pull-right.m-t-15
            = f.submit "Save", class: 'btn btn-primary w-lg btn-lg'

- if can? :manage, current_project
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        Delete project
    .panel-body
      = link_to "Delete", project_path(current_project), method: :delete,
        data: { confirm: "'#{current_project.name}' project will be deleted. Are you sure?" },
        class: 'btn btn-danger'

app/views/projects/show.html.haml
- breadcrumb :project, current_project

- content_for :page_title do
  Branches

- content_for :page_actions do
  = link_to new_project_branch_path(current_project),
    class: 'btn btn-xs btn-success' do
    %i.fa.fa-plus
    %span= 'Track a branch'

.panel.panel-default
  - if @branches.empty?
    .panel-heading

      = render partial: "no_branches",
        locals: { project: current_project}
  - else
    .panel-body
      .row
        .col-md-12.col-sm-12.col-xs-12
          .table-responsive
            %table.table
              %thead
                %tr
                  %th Branch
                  %th Latest Run Commit
                  %th Last run
                  %th Status
              %tbody
                - @branches.each do |branch|
                  %tr.branch
                    %td.col-md-3
                      .name
                        = link_to branch.branch_name,
                          project_branch_test_runs_path(branch.project, branch)
                    %td.col-md-5
                      - if branch.last_run
                        = branch.last_run.decorate.commit_message
                        %br
                        %i= branch.last_run.decorate.commit_info
                    %td.col-md-2
                      .time
                        - if branch.last_run.try(:completed_at)
                          = "#{time_ago_in_words(branch.last_run.completed_at)} ago"
                    %td.col-md-2
                      .status
                        %span{class: branch.status.try(:css_class)}
                          = branch.status.try(:text)